workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
  - build
  - deploy_preview
  - deploy_prod

default:
  before_script:
    - vercel telemetry disable

# ----- BUILD DOCKER IMAGE -------------------------

build_docker_image:
  stage: .pre
  image: docker:27
  services:
    - docker:27-dind
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  script:
    - docker version
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/vercel -f ci/Dockerfile .
    - docker image ls
    - docker push $CI_REGISTRY_IMAGE/vercel
    - exit 1

# ----- BUILD -------------------------

build_preview:
  stage: build
  image: $CI_REGISTRY_IMAGE/vercel
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
  script:
    - node --version
    - npm --version
    - vercel --version
    - vercel pull --yes --environment=preview --token $VERCEL_TOKEN
    - vercel build --token $VERCEL_TOKEN
  artifacts:
    untracked: true
    paths:
      - .vercel/output/
      - node_modules/

build_prod:
  stage: build
  image: $CI_REGISTRY_IMAGE/vercel
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      variables:
        VERCEL_ENVIRONMENT: 'production'
  script:
    - node --version
    - npm --version
    - vercel --version
    - vercel pull --yes --environment=production --token $VERCEL_TOKEN
    - vercel build --prod --token $VERCEL_TOKEN
  artifacts:
    untracked: true
    paths:
      - .vercel/output/
      - node_modules/

# ----- DEPLOY -------------------------

deploy_preview:
  stage: deploy_preview
  image: $CI_REGISTRY_IMAGE/vercel
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
  script:
    - vercel --version
    - vercel deploy --prebuilt --token $VERCEL_TOKEN

deploy_prod:
  stage: deploy_prod
  image: $CI_REGISTRY_IMAGE/vercel
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  script:
    - vercel --version
    - vercel deploy --prebuilt --prod --token $VERCEL_TOKEN
