workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: always

stages:
  - build
  - deploy_preview
  - deploy_prod

# ----- BUILD -------------------------

build_preview:
  image: node:22-alpine
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
  before_script:
    - npm install -g vercel
  script:
    - node --version
    - npm --version
    - vercel --version
    - vercel pull --yes --environment=preview --token $VERCEL_TOKEN
    - vercel build --token $VERCEL_TOKEN
  artifacts:
    untracked: true
    paths:
      - .vercel/output/
      - node_modules/

build_prod:
  image: node:22-alpine
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      variables:
        VERCEL_ENVIRONMENT: 'production'
  before_script:
    - npm install -g vercel
  script:
    - node --version
    - npm --version
    - vercel --version
    - vercel pull --yes --environment=production --token $VERCEL_TOKEN
    - vercel build --prod --token $VERCEL_TOKEN
  artifacts:
    untracked: true
    paths:
      - .vercel/output/
      - node_modules/

# ----- DEPLOY -------------------------

deploy_preview:
  image: node:22-alpine
  stage: deploy_preview
  rules:
    - if: '$CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
  before_script:
    - npm install -g vercel
  script:
    - vercel --version
    - vercel deploy --prebuilt --token $VERCEL_TOKEN

deploy_prod:
  image: node:22-alpine
  stage: deploy_prod
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  before_script:
    - npm install -g vercel
  script:
    - vercel --version
    - vercel deploy --prebuilt --prod --token $VERCEL_TOKEN
